import discord
from discord import app_commands
from discord.ext import commands
import os
import json
from datetime import datetime, timezone


TOKEN = os.getenv("DISCORD_TOKEN")
CONFIG_FILE = "config.json"

INTENTS = discord.Intents.default()
INTENTS.guilds = True
INTENTS.members = True
INTENTS.voice_states = True


DEFAULT_CONFIG = {
    "ticket": True,
    "ticket_category": None,
    "logs": False,
    "log_channel": None,
    "welcome": False,
    "welcome_channel": None,
    "welcome_message": "Hoş geldin {member}!",
    "autorole": False,
    "autorole_role": None,
    "moderation": True
}


LANGUAGES = {
    "tr": "🇹🇷 Türkçe",
    "en": "🇬🇧 English",
    "de": "🇩🇪 Deutsch",
    "fr": "🇫🇷 Français",
    "es": "🇪🇸 Español",
    "it": "🇮🇹 Italiano",
    "pt": "🇵🇹 Português",
    "ru": "🇷🇺 Русский",
    "ar": "🇸🇦 العربية",
    "zh": "🇨🇳 中文",
    "ja": "🇯🇵 日本語",
    "ko": "🇰🇷 한국어",
    "nl": "🇳🇱 Nederlands",
    "pl": "🇵🇱 Polski",
    "uk": "🇺🇦 Українська",
    "az": "🇦🇿 Azərbaycan"
}


TEXTS = {
    "tr": {
        "language_name": "Türkçe",
        "language_changed": "Diliniz Türkçe olarak ayarlandı.",
        "already_language": "Zaten Türkçe kullanıyorsunuz.",
        "language_title": "Dynex Dil Seçimi",
        "language_description": "Dynex'in kullanacağı dili seçin.",
        "settings_title": "Dynex Ayarları",
        "ticket": "🎫 Ticket",
        "logs": "📜 Loglar",
        "welcome": "👋 Hoş Geldin",
        "autorole": "👤 Otorol",
        "moderation": "🛡️ Moderasyon",
        "refresh": "🔄 Yenile",
        "reset": "♻️ Sıfırla",
        "enabled": "Açık",
        "disabled": "Kapalı",
        "ticket_open": "Ticket Aç",
        "ticket_close": "Ticket Kapat",
        "add_member": "Üye Ekle",
        "ticket_created": "Ticket oluşturuldu.",
        "ticket_closed": "Ticket kapatılıyor.",
        "ticket_disabled": "Ticket sistemi şu anda kapalı.",
        "ticket_name": "Ticket",
        "problem": "Sorun",
        "problem_placeholder": "Sorununuzu yazın",
        "member_id": "Üye ID",
        "member_id_placeholder": "Eklenecek üyenin Discord ID'si",
        "member_added": "Üye ticket'a eklendi.",
        "invalid_member": "Geçerli bir üye bulunamadı.",
        "permission": "Bu işlem için yeterli yetkiniz yok.",
        "saved": "Ayar kaydedildi.",
        "reset_done": "Sunucu ayarları sıfırlandı.",
        "ping_title": "Dynex Ping durumu",
        "ping_description": "**Dynex**'in ping durumu",
        "voice_title": "Ses Kanalı İstatistikleri",
        "voice_joined": "Katıldığı kanal",
        "voice_left": "Ayrıldığı kanal",
        "voice_duration": "Ses kanalında kalma süresi",
        "voice_members": "Çıkış anındaki üye sayısı",
        "voice_disable": "🔕 Ses Bildirimlerini Kapat",
        "voice_enable": "🔔 Ses Bildirimlerini Aç",
        "voice_disabled": "Ses bildirimleri kapatıldı.",
        "voice_enabled": "Ses bildirimleri açıldı.",
        "welcome_default": "Hoş geldin {member}!",
        "yes": "Evet",
        "no": "Hayır"
    },

    "en": {
        "language_name": "English",
        "language_changed": "Your language has been set to English.",
        "already_language": "You are already using English.",
        "language_title": "Dynex Language Selection",
        "language_description": "Select the language Dynex should use.",
        "settings_title": "Dynex Settings",
        "ticket": "🎫 Ticket",
        "logs": "📜 Logs",
        "welcome": "👋 Welcome",
        "autorole": "👤 Autorole",
        "moderation": "🛡️ Moderation",
        "refresh": "🔄 Refresh",
        "reset": "♻️ Reset",
        "enabled": "Enabled",
        "disabled": "Disabled",
        "ticket_open": "Open Ticket",
        "ticket_close": "Close Ticket",
        "add_member": "Add Member",
        "ticket_created": "Ticket created.",
        "ticket_closed": "The ticket is being closed.",
        "ticket_disabled": "The ticket system is currently disabled.",
        "ticket_name": "Ticket",
        "problem": "Problem",
        "problem_placeholder": "Describe your problem",
        "member_id": "Member ID",
        "member_id_placeholder": "Discord ID of the member to add",
        "member_added": "The member was added to the ticket.",
        "invalid_member": "No valid member was found.",
        "permission": "You do not have permission to do this.",
        "saved": "Setting saved.",
        "reset_done": "Server settings have been reset.",
        "ping_title": "Dynex Ping Status",
        "ping_description": "**Dynex**'s ping status",
        "voice_title": "Voice Channel Statistics",
        "voice_joined": "Joined channel",
        "voice_left": "Left channel",
        "voice_duration": "Time spent in voice",
        "voice_members": "Members when leaving",
        "voice_disable": "🔕 Disable Voice Notifications",
        "voice_enable": "🔔 Enable Voice Notifications",
        "voice_disabled": "Voice notifications have been disabled.",
        "voice_enabled": "Voice notifications have been enabled.",
        "welcome_default": "Welcome {member}!",
        "yes": "Yes",
        "no": "No"
    },

    "de": {
        "language_name": "Deutsch",
        "language_changed": "Deine Sprache wurde auf Deutsch eingestellt.",
        "already_language": "Du verwendest bereits Deutsch.",
        "language_title": "Dynex Sprachauswahl",
        "language_description": "Wähle die Sprache für Dynex.",
        "settings_title": "Dynex Einstellungen",
        "ticket": "🎫 Ticket",
        "logs": "📜 Logs",
        "welcome": "👋 Willkommen",
        "autorole": "👤 Autorolle",
        "moderation": "🛡️ Moderation",
        "refresh": "🔄 Aktualisieren",
        "reset": "♻️ Zurücksetzen",
        "enabled": "Aktiv",
        "disabled": "Deaktiviert",
        "ticket_open": "Ticket öffnen",
        "ticket_close": "Ticket schließen",
        "add_member": "Mitglied hinzufügen",
        "ticket_created": "Ticket erstellt.",
        "ticket_closed": "Das Ticket wird geschlossen.",
        "ticket_disabled": "Das Ticketsystem ist derzeit deaktiviert.",
        "ticket_name": "Ticket",
        "problem": "Problem",
        "problem_placeholder": "Beschreibe dein Problem",
        "member_id": "Mitglieds-ID",
        "member_id_placeholder": "Discord-ID des Mitglieds",
        "member_added": "Mitglied wurde hinzugefügt.",
        "invalid_member": "Kein gültiges Mitglied gefunden.",
        "permission": "Du hast keine Berechtigung.",
        "saved": "Einstellung gespeichert.",
        "reset_done": "Servereinstellungen wurden zurückgesetzt.",
        "ping_title": "Dynex Ping-Status",
        "ping_description": "Der Ping-Status von **Dynex**",
        "voice_title": "Sprachkanal-Statistiken",
        "voice_joined": "Beigetretener Kanal",
        "voice_left": "Verlassener Kanal",
        "voice_duration": "Zeit im Sprachkanal",
        "voice_members": "Mitglieder beim Verlassen",
        "voice_disable": "🔕 Sprachbenachrichtigungen deaktivieren",
        "voice_enable": "🔔 Sprachbenachrichtigungen aktivieren",
        "voice_disabled": "Sprachbenachrichtigungen wurden deaktiviert.",
        "voice_enabled": "Sprachbenachrichtigungen wurden aktiviert.",
        "welcome_default": "Willkommen {member}!",
        "yes": "Ja",
        "no": "Nein"
    },

    "fr": {
        "language_name": "Français",
        "language_changed": "Votre langue est maintenant le français.",
        "already_language": "Vous utilisez déjà le français.",
        "language_title": "Choix de la langue Dynex",
        "language_description": "Choisissez la langue de Dynex.",
        "settings_title": "Paramètres Dynex",
        "ticket": "🎫 Ticket",
        "logs": "📜 Logs",
        "welcome": "👋 Bienvenue",
        "autorole": "👤 Rôle automatique",
        "moderation": "🛡️ Modération",
        "refresh": "🔄 Actualiser",
        "reset": "♻️ Réinitialiser",
        "enabled": "Activé",
        "disabled": "Désactivé",
        "ticket_open": "Ouvrir un ticket",
        "ticket_close": "Fermer le ticket",
        "add_member": "Ajouter un membre",
        "ticket_created": "Ticket créé.",
        "ticket_closed": "Le ticket va être fermé.",
        "ticket_disabled": "Le système de tickets est actuellement désactivé.",
        "ticket_name": "Ticket",
        "problem": "Problème",
        "problem_placeholder": "Décrivez votre problème",
        "member_id": "ID du membre",
        "member_id_placeholder": "ID Discord du membre",
        "member_added": "Le membre a été ajouté.",
        "invalid_member": "Aucun membre valide trouvé.",
        "permission": "Vous n'avez pas la permission.",
        "saved": "Paramètre enregistré.",
        "reset_done": "Les paramètres du serveur ont été réinitialisés.",
        "ping_title": "État du ping Dynex",
        "ping_description": "État du ping de **Dynex**",
        "voice_title": "Statistiques vocales",
        "voice_joined": "Salon rejoint",
        "voice_left": "Salon quitté",
        "voice_duration": "Temps passé en vocal",
        "voice_members": "Membres au départ",
        "voice_disable": "🔕 Désactiver les notifications vocales",
        "voice_enable": "🔔 Activer les notifications vocales",
        "voice_disabled": "Les notifications vocales sont désactivées.",
        "voice_enabled": "Les notifications vocales sont activées.",
        "welcome_default": "Bienvenue {member}!",
        "yes": "Oui",
        "no": "Non"
    },

    "es": {
        "language_name": "Español",
        "language_changed": "Tu idioma ahora es español.",
        "already_language": "Ya estás usando español.",
        "language_title": "Idioma de Dynex",
        "language_description": "Selecciona el idioma de Dynex.",
        "settings_title": "Configuración de Dynex",
        "ticket": "🎫 Ticket",
        "logs": "📜 Registros",
        "welcome": "👋 Bienvenida",
        "autorole": "👤 Autorol",
        "moderation": "🛡️ Moderación",
        "refresh": "🔄 Actualizar",
        "reset": "♻️ Restablecer",
        "enabled": "Activado",
        "disabled": "Desactivado",
        "ticket_open": "Abrir ticket",
        "ticket_close": "Cerrar ticket",
        "add_member": "Añadir miembro",
        "ticket_created": "Ticket creado.",
        "ticket_closed": "El ticket se está cerrando.",
        "ticket_disabled": "El sistema de tickets está desactivado.",
        "ticket_name": "Ticket",
        "problem": "Problema",
        "problem_placeholder": "Describe tu problema",
        "member_id": "ID del miembro",
        "member_id_placeholder": "ID de Discord del miembro",
        "member_added": "El miembro fue añadido.",
        "invalid_member": "No se encontró un miembro válido.",
        "permission": "No tienes permiso.",
        "saved": "Configuración guardada.",
        "reset_done": "Configuración del servidor restablecida.",
        "ping_title": "Estado del Ping de Dynex",
        "ping_description": "Estado del ping de **Dynex**",
        "voice_title": "Estadísticas de voz",
        "voice_joined": "Canal al que entró",
        "voice_left": "Canal del que salió",
        "voice_duration": "Tiempo en voz",
        "voice_members": "Miembros al salir",
        "voice_disable": "🔕 Desactivar notificaciones de voz",
        "voice_enable": "🔔 Activar notificaciones de voz",
        "voice_disabled": "Notificaciones de voz desactivadas.",
        "voice_enabled": "Notificaciones de voz activadas.",
        "welcome_default": "¡Bienvenido {member}!",
        "yes": "Sí",
        "no": "No"
    },

    "it": {
        "language_name": "Italiano",
        "language_changed": "La tua lingua è stata impostata su Italiano.",
        "already_language": "Stai già usando Italiano.",
        "language_title": "Lingua Dynex",
        "language_description": "Seleziona la lingua di Dynex.",
        "settings_title": "Impostazioni Dynex",
        "ticket": "🎫 Ticket",
        "logs": "📜 Log",
        "welcome": "👋 Benvenuto",
        "autorole": "👤 Autorole",
        "moderation": "🛡️ Moderazione",
        "refresh": "🔄 Aggiorna",
        "reset": "♻️ Ripristina",
        "enabled": "Attivo",
        "disabled": "Disattivato",
        "ticket_open": "Apri ticket",
        "ticket_close": "Chiudi ticket",
        "add_member": "Aggiungi membro",
        "ticket_created": "Ticket creato.",
        "ticket_closed": "Il ticket verrà chiuso.",
        "ticket_disabled": "Il sistema ticket è disattivato.",
        "ticket_name": "Ticket",
        "problem": "Problema",
        "problem_placeholder": "Descrivi il problema",
        "member_id": "ID membro",
        "member_id_placeholder": "ID Discord del membro",
        "member_added": "Membro aggiunto.",
        "invalid_member": "Nessun membro valido trovato.",
        "permission": "Non hai il permesso.",
        "saved": "Impostazione salvata.",
        "reset_done": "Impostazioni del server ripristinate.",
        "ping_title": "Stato Ping Dynex",
        "ping_description": "Stato del ping di **Dynex**",
        "voice_title": "Statistiche canale vocale",
        "voice_joined": "Canale di ingresso",
        "voice_left": "Canale di uscita",
        "voice_duration": "Tempo in vocale",
        "voice_members": "Membri all'uscita",
        "voice_disable": "🔕 Disattiva notifiche vocali",
        "voice_enable": "🔔 Attiva notifiche vocali",
        "voice_disabled": "Notifiche vocali disattivate.",
        "voice_enabled": "Notifiche vocali attivate.",
        "welcome_default": "Benvenuto {member}!",
        "yes": "Sì",
        "no": "No"
    },

    "pt": {
        "language_name": "Português",
        "language_changed": "Seu idioma foi definido como Português.",
        "already_language": "Você já está usando Português.",
        "language_title": "Idioma do Dynex",
        "language_description": "Selecione o idioma do Dynex.",
        "settings_title": "Configurações do Dynex",
        "ticket": "🎫 Ticket",
        "logs": "📜 Logs",
        "welcome": "👋 Boas-vindas",
        "autorole": "👤 Autorole",
        "moderation": "🛡️ Moderação",
        "refresh": "🔄 Atualizar",
        "reset": "♻️ Redefinir",
        "enabled": "Ativado",
        "disabled": "Desativado",
        "ticket_open": "Abrir ticket",
        "ticket_close": "Fechar ticket",
        "add_member": "Adicionar membro",
        "ticket_created": "Ticket criado.",
        "ticket_closed": "O ticket está sendo fechado.",
        "ticket_disabled": "O sistema de tickets está desativado.",
        "ticket_name": "Ticket",
        "problem": "Problema",
        "problem_placeholder": "Descreva seu problema",
        "member_id": "ID do membro",
        "member_id_placeholder": "ID Discord do membro",
        "member_added": "Membro adicionado.",
        "invalid_member": "Nenhum membro válido encontrado.",
        "permission": "Você não tem permissão.",
        "saved": "Configuração salva.",
        "reset_done": "Configurações do servidor redefinidas.",
        "ping_title": "Status do Ping do Dynex",
        "ping_description": "Status do ping do **Dynex**",
        "voice_title": "Estatísticas de voz",
        "voice_joined": "Canal de entrada",
        "voice_left": "Canal de saída",
        "voice_duration": "Tempo em voz",
        "voice_members": "Membros ao sair",
        "voice_disable": "🔕 Desativar notificações de voz",
        "voice_enable": "🔔 Ativar notificações de voz",
        "voice_disabled": "Notificações de voz desativadas.",
        "voice_enabled": "Notificações de voz ativadas.",
        "welcome_default": "Bem-vindo {member}!",
        "yes": "Sim",
        "no": "Não"
    },

    "ru": {
        "language_name": "Русский",
        "language_changed": "Ваш язык установлен на русский.",
        "already_language": "Вы уже используете русский.",
        "language_title": "Язык Dynex",
        "language_description": "Выберите язык Dynex.",
        "settings_title": "Настройки Dynex",
        "ticket": "🎫 Тикет",
        "logs": "📜 Логи",
        "welcome": "👋 Приветствие",
        "autorole": "👤 Автороль",
        "moderation": "🛡️ Модерация",
        "refresh": "🔄 Обновить",
        "reset": "♻️ Сбросить",
        "enabled": "Включено",
        "disabled": "Выключено",
        "ticket_open": "Открыть тикет",
        "ticket_close": "Закрыть тикет",
        "add_member": "Добавить участника",
        "ticket_created": "Тикет создан.",
        "ticket_closed": "Тикет закрывается.",
        "ticket_disabled": "Система тикетов отключена.",
        "ticket_name": "Тикет",
        "problem": "Проблема",
        "problem_placeholder": "Опишите проблему",
        "member_id": "ID участника",
        "member_id_placeholder": "Discord ID участника",
        "member_added": "Участник добавлен.",
        "invalid_member": "Участник не найден.",
        "permission": "У вас нет прав.",
        "saved": "Настройка сохранена.",
        "reset_done": "Настройки сервера сброшены.",
        "ping_title": "Статус Ping Dynex",
        "ping_description": "Статус ping **Dynex**",
        "voice_title": "Статистика голосового канала",
        "voice_joined": "Канал входа",
        "voice_left": "Канал выхода",
        "voice_duration": "Время в голосовом канале",
        "voice_members": "Участников при выходе",
        "voice_disable": "🔕 Отключить голосовые уведомления",
        "voice_enable": "🔔 Включить голосовые уведомления",
        "voice_disabled": "Голосовые уведомления отключены.",
        "voice_enabled": "Голосовые уведомления включены.",
        "welcome_default": "Добро пожаловать, {member}!",
        "yes": "Да",
        "no": "Нет"
    },

    "ar": {
        "language_name": "العربية",
        "language_changed": "تم ضبط لغتك على العربية.",
        "already_language": "أنت تستخدم العربية بالفعل.",
        "language_title": "لغة Dynex",
        "language_description": "اختر لغة Dynex.",
        "settings_title": "إعدادات Dynex",
        "ticket": "🎫 تذكرة",
        "logs": "📜 السجلات",
        "welcome": "👋 الترحيب",
        "autorole": "👤 رتبة تلقائية",
        "moderation": "🛡️ الإشراف",
        "refresh": "🔄 تحديث",
        "reset": "♻️ إعادة ضبط",
        "enabled": "مفعّل",
        "disabled": "معطّل",
        "ticket_open": "فتح تذكرة",
        "ticket_close": "إغلاق التذكرة",
        "add_member": "إضافة عضو",
        "ticket_created": "تم إنشاء التذكرة.",
        "ticket_closed": "جارٍ إغلاق التذكرة.",
        "ticket_disabled": "نظام التذاكر معطّل حالياً.",
        "ticket_name": "تذكرة",
        "problem": "المشكلة",
        "problem_placeholder": "اكتب مشكلتك",
        "member_id": "معرّف العضو",
        "member_id_placeholder": "معرّف Discord للعضو",
        "member_added": "تمت إضافة العضو.",
        "invalid_member": "لم يتم العثور على عضو صالح.",
        "permission": "ليس لديك صلاحية.",
        "saved": "تم حفظ الإعداد.",
        "reset_done": "تمت إعادة ضبط إعدادات الخادم.",
        "ping_title": "حالة Ping لـ Dynex",
        "ping_description": "حالة Ping الخاصة بـ **Dynex**",
        "voice_title": "إحصائيات القناة الصوتية",
        "voice_joined": "القناة التي انضم إليها",
        "voice_left": "القناة التي غادرها",
        "voice_duration": "مدة البقاء في الصوت",
        "voice_members": "الأعضاء عند المغادرة",
        "voice_disable": "🔕 تعطيل إشعارات الصوت",
        "voice_enable": "🔔 تفعيل إشعارات الصوت",
        "voice_disabled": "تم تعطيل إشعارات الصوت.",
        "voice_enabled": "تم تفعيل إشعارات الصوت.",
        "welcome_default": "مرحباً {member}!",
        "yes": "نعم",
        "no": "لا"
    },

    "zh": {
        "language_name": "中文",
        "language_changed": "您的语言已设置为中文。",
        "already_language": "您已经在使用中文。",
        "language_title": "Dynex 语言选择",
        "language_description": "选择 Dynex 使用的语言。",
        "settings_title": "Dynex 设置",
        "ticket": "🎫 工单",
        "logs": "📜 日志",
        "welcome": "👋 欢迎",
        "autorole": "👤 自动身份组",
        "moderation": "🛡️ 管理",
        "refresh": "🔄 刷新",
        "reset": "♻️ 重置",
        "enabled": "已开启",
        "disabled": "已关闭",
        "ticket_open": "打开工单",
        "ticket_close": "关闭工单",
        "add_member": "添加成员",
        "ticket_created": "工单已创建。",
        "ticket_closed": "工单正在关闭。",
        "ticket_disabled": "工单系统目前已关闭。",
        "ticket_name": "工单",
        "problem": "问题",
        "problem_placeholder": "描述您的问题",
        "member_id": "成员 ID",
        "member_id_placeholder": "要添加成员的 Discord ID",
        "member_added": "成员已添加。",
        "invalid_member": "未找到有效成员。",
        "permission": "您没有权限。",
        "saved": "设置已保存。",
        "reset_done": "服务器设置已重置。",
        "ping_title": "Dynex Ping 状态",
        "ping_description": "**Dynex** 的 Ping 状态",
        "voice_title": "语音频道统计",
        "voice_joined": "加入的频道",
        "voice_left": "离开的频道",
        "voice_duration": "语音停留时间",
        "voice_members": "离开时成员数",
        "voice_disable": "🔕 关闭语音通知",
        "voice_enable": "🔔 开启语音通知",
        "voice_disabled": "语音通知已关闭。",
        "voice_enabled": "语音通知已开启。",
        "welcome_default": "欢迎 {member}！",
        "yes": "是",
        "no": "否"
    },

    "ja": {
        "language_name": "日本語",
        "language_changed": "言語を日本語に設定しました。",
        "already_language": "すでに日本語を使用しています。",
        "language_title": "Dynex 言語選択",
        "language_description": "Dynex の言語を選択してください。",
        "settings_title": "Dynex 設定",
        "ticket": "🎫 チケット",
        "logs": "📜 ログ",
        "welcome": "👋 ウェルカム",
        "autorole": "👤 自動ロール",
        "moderation": "🛡️ モデレーション",
        "refresh": "🔄 更新",
        "reset": "♻️ リセット",
        "enabled": "有効",
        "disabled": "無効",
        "ticket_open": "チケットを開く",
        "ticket_close": "チケットを閉じる",
        "add_member": "メンバーを追加",
        "ticket_created": "チケットを作成しました。",
        "ticket_closed": "チケットを閉じています。",
        "ticket_disabled": "チケットシステムは現在無効です。",
        "ticket_name": "チケット",
        "problem": "問題",
        "problem_placeholder": "問題を入力してください",
        "member_id": "メンバーID",
        "member_id_placeholder": "追加するメンバーのDiscord ID",
        "member_added": "メンバーを追加しました。",
        "invalid_member": "有効なメンバーが見つかりません。",
        "permission": "権限がありません。",
        "saved": "設定を保存しました。",
        "reset_done": "サーバー設定をリセットしました。",
        "ping_title": "Dynex Ping 状態",
        "ping_description": "**Dynex** の Ping 状態",
        "voice_title": "ボイスチャンネル統計",
